### PR TITLE
⬆️ Upgrade dependancies

### PR DESCRIPTION
**Pull request by WeiJun0827**

### CODE REVIEW

**Comment by williamchong** [comment]
conflict and hard to keep track of what package is updated, can we also update `package.json` to know which one is actually updated?

**Comment by WeiJun0827** [comment]
Because GitHub complains that there have some potential security vulnerabilities in the dependencies. I plan to fix this but keep the `package.json` version's consistency. Is using `yarn upgrade` OK for our case?

**Comment by WeiJun0827** [comment]
I think it does not.

**Comment by williamchong** [comment]
I think
```arweave@^1.10.13, arweave@^1.10.18:
  version "1.10.18"
  resolved "https://registry.yarnpkg.com/arweave/-/arweave-1.10.18.tgz#3042edd1afa52b7c3caeacf88271758232c7b866"
  integrity sha512-i3pKBkLtU1Jl9RtJ9A6zgz8QqF5FZy7YA+qGQ9i2Zug171p29FTDZhN+KlRcVBg8sEgd1DKyecCCYJZ3K6Jdfg==
  version "1.10.23"
  resolved "https://registry.yarnpkg.com/arweave/-/arweave-1.10.23.tgz#6edc056026d6c11ec47d817bb2c4f6d8fb8c65e5"
  integrity sha512-lAeCopS9iNGhmJkUovWqb7R+JEF83LP8f51rG+H98JPI9KQVRJYtM5NmMMU8auDtOzvBPTZ7me1pYn/CfS3VTg==```
  
  ```bignumber.js@^9.0.1:
  version "9.0.1"
  resolved "https://registry.yarnpkg.com/bignumber.js/-/bignumber.js-9.0.1.tgz#8d7ba124c882bfd8e43260c67475518d0689e4e5"
  integrity sha512-IdZR9mh6ahOBv/hYGiXyVuyCetmGJhtYkqLBpTStdhEGjegpPlUawydyaF3pbIOFynJTpllEs+NP+CS9jKFLjA==
  version "9.0.2"
  resolved "https://registry.yarnpkg.com/bignumber.js/-/bignumber.js-9.0.2.tgz#71c6c6bed38de64e24a65ebe16cfcf23ae693673"
  integrity sha512-GAcQvbpsM0pUb0zw1EI0KhQEZ+lRwR5fYaAp3vPOYuP7aDvGy6cVN6XHLauvF8SOga2y0dcLcjt3iQDTSEliyw==```
  
  are listed in package.json, would be nice if we can update entry like this in package.json to the updated version also, but seems very troublesome work to do...

**Comment by WeiJun0827** [comment]
It's OK not to upgrade whole dependencies with `yarn upgrade`. But should we need to fix these warnings?
https://github.com/likecoin/arweave-uploader/security/dependabot

**Pull request closed without merging**
